import { Roboto } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/Context/useAuth"; // Certifique-se de importar o UserProvider

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <UserProvider> {/* Certifique-se de envolver o conteúdo com UserProvider */}
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
